// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rotating.Models;

namespace rotating.Migrations.User
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("rotating.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nip")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2020, 12, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            email = "yulianti@pertamina.com",
                            name = "Yulianti Eka Prista",
                            nip = 194020001,
                            password = "7cUDtt084TSg1vUyltg+xJHXaa+ZQvxJgGKMIZ7cvaA=",
                            phone = "08821389745",
                            role = "engineer",
                            status = 1,
                            updated_at = new DateTime(2020, 12, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2020, 12, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            email = "pratama@pertamina.com",
                            name = "Pratama Edi Saputra",
                            nip = 194020002,
                            password = "7cUDtt084TSg1vUyltg+xJHXaa+ZQvxJgGKMIZ7cvaA=",
                            phone = "087985298445",
                            role = "engineer",
                            status = 1,
                            updated_at = new DateTime(2020, 12, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2020, 12, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            email = "safril@pertamina.com",
                            name = "Safril Sidik",
                            nip = 194020003,
                            password = "7cUDtt084TSg1vUyltg+xJHXaa+ZQvxJgGKMIZ7cvaA=",
                            phone = "088213669701",
                            role = "admin",
                            status = 1,
                            updated_at = new DateTime(2020, 12, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
